# Generated by Django 4.0 on 2024-09-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=20)),
                ('empname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('joined_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
